05-lection3/01 add tooltip
js-tasks-ru/htmlcss-20231222_lv-khomyakova pull request #11
Opened 2024-01-20 15:19 UTC by LVKhomyakova

2024-01-20 15:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-21 14:51 UTC, GSemikozov approved these changes

2024-01-21 14:51 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-01-21 14:52 UTC, GSemikozov requested changes
надо бы поправить конфликт

2024-01-25 21:16 UTC, GSemikozov approved these changes

2024-01-25 21:16 UTC, merged