03 lection1/01 button
js-tasks-ru/htmlcss-20231222_lv-khomyakova pull request #4
Opened 2024-01-12 12:21 UTC by LVKhomyakova

2024-01-12 12:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-14 17:02 UTC, GSemikozov requested changes

2024-01-14 17:02 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
не хватает font-family)

2024-01-14 17:02 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
а так - все ок

2024-01-14 17:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-15 22:21 UTC, GSemikozov approved these changes

2024-01-15 22:22 UTC, merged