03-lection1/01 add main page
js-tasks-ru/htmlcss-20231222_lv-khomyakova pull request #6
Opened 2024-01-15 19:56 UTC by LVKhomyakova

2024-01-15 19:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-15 22:23 UTC, GSemikozov requested changes
и еще - конфликт

2024-01-15 22:23 UTC, GSemikozov commented on components/footer/footer.css
> +    position: fixed;
ой, это не надо

2024-01-15 22:23 UTC, GSemikozov commented on components/footer/footer.css
> +    width: 100%;
лишнее (блочный и так на 100% потянется)

2024-01-15 22:23 UTC, GSemikozov commented on components/footer/footer.css
> +    width: 640px;
max-width

2024-01-15 22:23 UTC, GSemikozov commented on components/header/header.css
> +    position: sticky;
в нашем случае - не нужно

2024-01-15 22:23 UTC, GSemikozov commented on components/header/header.css
> +    padding: 96px 160px 78px;
вместо таких паддингов по краям - лучше использовать container )

2024-01-15 22:23 UTC, GSemikozov commented on components/preview/preview.css
> +    height: 100%;
лишнее

2024-01-16 07:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-16 07:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-01-16 21:13 UTC, GSemikozov approved these changes

2024-01-16 21:13 UTC, merged