04-lection2/01 add histogram
js-tasks-ru/htmlcss-20231222_lv-khomyakova pull request #7
Opened 2024-01-16 14:10 UTC by LVKhomyakova

2024-01-16 14:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-16 21:15 UTC, GSemikozov requested changes

2024-01-16 21:15 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    text-decoration: none;
margin-top: 3px?

2024-01-16 21:15 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    row-gap: 40px;
39

2024-01-17 06:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-17 12:14 UTC, GSemikozov approved these changes

2024-01-17 12:14 UTC, merged